# Generated by Django 5.2.15 on 2026-06-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('address', models.TextField(verbose_name='عنوان التوصيل')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات على الطلب')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الصنف')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='رسوم التوصيل')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المبلغ الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='restaurant.dish', verbose_name='الطبق')),
            ],
            options={
                'verbose_name': 'طلب توصيل',
                'verbose_name_plural': 'طلبات التوصيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
