# Generated by Django 5.2.15 on 2026-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_deliveryorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='صورة العميل'),
        ),
    ]
