# Generated by Django 5.2.15 on 2026-06-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='dish',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الحجز'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
    ]
